### ISSUE TITLE
Model links not accessible.

### ISSUE THREAD

**Issue by LexTypeC** [Lllmmr/Image-Blending-GUI#2]
The Pecking University link appears to have expired and the Baidu link is not accessible for those outside of China. May I request that an accessible link is added.

**Comment by Lllmmr** [comment]
> The Pecking University link appears to have expired and the Baidu link is not accessible for those outside of China. May I request that an accessible link is added.

The model file has been uploaded to release now.

**Comment by LexTypeC** [comment]
Perfect, thank you!
